_format_version: "3.0"
services:
- host: host.docker.internal
  name: films-api
  port: 9000
  protocol: grpc
  routes:
  - name: http-routes
    paths:
    - /api
    plugins:
    - config:
        proto: /usr/local/kong/service-1.films.proto
      name: grpc-gateway
      protocols:
      - grpc
      - grpcs
      - http
      - https
    - config:
        ai_metrics: false
        bandwidth_metrics: true
        latency_metrics: true
        per_consumer: true
        status_code_metrics: true
        upstream_health_metrics: true
      name: prometheus
      protocols:
      - grpc
      - grpcs
      - http
      - https
    protocols:
    - http
    strip_path: true
- host: host.docker.internal
  name: films-grpc-api
  port: 9111
  protocol: grpc
  routes:
  - name: grpc-gateway
    paths:
    - /grpc.v1.Service1
    plugins:
    - config:
        ai_metrics: false
        bandwidth_metrics: true
        latency_metrics: true
        per_consumer: true
        status_code_metrics: true
        upstream_health_metrics: true
      name: prometheus
      protocols:
      - grpc
      - grpcs
      - http
      - https
    protocols:
    - grpc
    strip_path: false
